import matplotlib.pyplot as plt
import numpy as np
import sys
import os


def load_profiles(filename):
    """Load u(y) and v(x) profiles from the CSV generated by the cavity benchmark."""
    y_u, x_v = [], []
    current_mode = None
    with open(filename, 'r') as f:
        for line in f:
            if "Vertical centerline" in line:
                current_mode = "u"
            elif "Horizontal centerline" in line:
                current_mode = "v"
            elif line.startswith("#") or not line.strip():
                continue
            else:
                vals = [float(x) for x in line.split(",")]
                if current_mode == "u":
                    y_u.append(vals)
                else:
                    x_v.append(vals)
    return np.array(y_u), np.array(x_v)


# Ghia et al. (1982) reference data for Re = 100
# y/N coordinates and u/U_lid at the vertical centerline (x = N/2)
ghia_y = np.array([1.0, 0.9766, 0.9688, 0.9609, 0.9531, 0.8516, 0.7344,
                   0.6172, 0.5000, 0.4531, 0.2813, 0.1719, 0.1016,
                   0.0703, 0.0625, 0.0547, 0.0])
ghia_u = np.array([1.0, 0.84123, 0.78871, 0.73722, 0.68717, 0.23151,
                   0.00332, -0.13641, -0.20581, -0.21090, -0.15662,
                   -0.10150, -0.06434, -0.04775, -0.04192, -0.03717, 0.0])

# Ghia reference data for the horizontal centerline (y = N/2) — v/U_lid vs x/N
ghia_x = np.array([0.0, 0.0625, 0.0703, 0.0781, 0.0938, 0.1563, 0.2266,
                   0.2344, 0.5000, 0.8047, 0.8594, 0.9063, 0.9453,
                   0.9531, 0.9609, 0.9688, 0.9766, 1.0])
ghia_v = np.array([0.0, -0.06080, -0.06734, -0.07404, -0.08811, -0.15879,
                   -0.19964, -0.20066, -0.00000, 0.19964, 0.17579, 0.13903,
                   0.05145, 0.04012, 0.02924, 0.01687, 0.00823, 0.0])


def main():
    # Parse CSV files from command-line arguments or use defaults
    files = sys.argv[1:] if len(sys.argv) > 1 else [
        "../saves/cavity_Re100_N32.csv",
        "../saves/cavity_Re100_N64.csv",
        "../saves/cavity_Re100_N128.csv",
        # "../saves/cavity_Re400_N256.csv"
    ]

    fig, (ax_u, ax_v) = plt.subplots(1, 2, figsize=(14, 6))

    # --- u-velocity profile (vertical centerline, x = N/2) ---
    ax_u.plot(ghia_u, ghia_y, 'ro', label='Ghia et al. (1982) Re=100',
              markersize=6, zorder=5)

    linestyles = ['b--', 'g-', 'm:', 'c-.']
    for i, fpath in enumerate(files):
        if not os.path.exists(fpath):
            print(f"Warning: {fpath} not found, skipping")
            continue
        y_u, x_v = load_profiles(fpath)

        if len(y_u) == 0:
            continue

        # y_u[:, 0] = y/N (0 at top lid), so 1 - y/N matches Ghia (0 at bottom)
        label = os.path.basename(fpath).replace(".csv", "")
        ax_u.plot(y_u[:, 1], 1 - y_u[:, 0],
                  linestyles[i % len(linestyles)], label=label)

    ax_u.set_title('Horizontal Velocity u(y) at x = N/2')
    ax_u.set_xlabel('u / U_lid')
    ax_u.set_ylabel('y / N')
    ax_u.grid(True, alpha=0.3)
    ax_u.legend()

    # --- v-velocity profile (horizontal centerline, y = N/2) ---
    ax_v.plot(ghia_x, ghia_v, 'ro', markersize=6, zorder=5,
              label='Ghia et al. (1982) Re=100')

    for i, fpath in enumerate(files):
        if not os.path.exists(fpath):
            continue
        y_u, x_v = load_profiles(fpath)

        if len(x_v) == 0:
            continue

        label = os.path.basename(fpath).replace(".csv", "")
        ax_v.plot(x_v[:, 0], x_v[:, 1],
                  linestyles[i % len(linestyles)], label=label)

    ax_v.set_title('Vertical Velocity v(x) at y = N/2')
    ax_v.set_xlabel('x / N')
    ax_v.set_ylabel('v / U_lid')
    ax_v.grid(True, alpha=0.3)
    ax_v.legend()

    plt.suptitle('Lid-Driven Cavity Benchmark — Comparison with Ghia et al. (1982)',
                 fontsize=14)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
